name: vraz_application
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # File and Image Pickers
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  path_provider: ^2.1.3

  # Audio Recording and Playback
  flutter_sound: ^9.2.13
  just_audio: ^0.10.5

  # State Management & Utils
  provider: ^6.1.2
  intl: ^0.20.2

  # Video and Network
  youtube_player_flutter: ^9.0.1
  http: ^1.2.1
  video_player: ^2.8.6

  # Local Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  args: ^2.7.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0  # ðŸ‘ˆ ADDED THIS LINE
  url_launcher: ^6.3.2
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Register asset folders
  assets:
    - assets/
